theme = "hugo-ivy"
baseURL = "https://yiyuan.vercel.app/"
languageCode = "en-us"
title = "略略"


menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4
    - name: "Subscribe"
      url: "/index.xml"
      
  
  
## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "yuanyiyy/BlogComments" 
  issueTerm = "pathname"
  theme = "github-light"  
